import Head from "next/head";
import Image from "next/image";
// import { useState } from "react";
import styles from "../styles/Home.module.css";
import Header from "../components/main/Header";
import PostsHeader from "../components/posts/PostsHeader";
import Preview from "../components/posts/Preview";
import useSWR from "swr";
import axios from "axios";

// import { useAuth } from "../components/auth/AuthContext";

export default function Home() {

  const fetcher = (url) =>
    axios({
      method: "get",
      url: url,
    }).then((res) => {
      return res.data;
    });

  const { data, error } = useSWR(
    process.env.NEXT_PUBLIC_API_ROUTE + "api/posts",
    fetcher
  );


  return (
    <div className={styles.container}>
      <Head>
        <title>Launchable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PostsHeader />
      {data && data.data.map((post) => (
        <Preview
          title={post.title}
          user={post.user}
          likes={post.likes}
          commentsCount={post.comments_count}
        />
      ))}
      <br />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          2022, Launchable by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
