import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Login.module.css";
import { useState, useEffect } from "react";
import Header from "../components/main/Header";
import { Input, Button, FormControl } from "@chakra-ui/react";
import {
  signInWithEmailAndPassword,
  signOut,
  signInWithPopup,
  GoogleAuthProvider,
  TwitterAuthProvider,
} from "firebase/auth";
import auth from "../config/firebase";
import { Formik, Form, Field } from "formik";
import MainButton from "../components/assets/MainButton";
import { FcGoogle } from "react-icons/fc";
import { FaTwitter, FaFacebookSquare } from "react-icons/fa";
import axios from "axios";
import { useAuth } from "../components/auth/AuthContext";

const googleProvider = new GoogleAuthProvider();
const twitterProvider = new TwitterAuthProvider();

function validateName(value) {
  let error;
  if (!value) {
    error = "Name is required";
  }
  return error;
}

export default function Login() {
  const router = useRouter();
  const { currentUser } = useAuth();
  if (currentUser) router.push("/");

  const handleResize = () => {
    if (window.innerWidth < 544) {
      setIsWidthMinimized(true);
    } else {
      setIsWidthMinimized(false);
    }
  };

  useEffect(() => {
    window.addEventListener("resize", handleResize);
  });

  const [isWidthMinimized, setIsWidthMinimized] = useState(false);

  const checkIfUserIdExists = (id) => {
    axios({
      method: "post",
      url: process.env.NEXT_PUBLIC_API_ROUTE + "api/auth",
      data: JSON.stringify({
        id: id,
      }),
      headers: {
        "Content-Type": "application/json",
      },
    }).then((res) => {
      if (res.data.userExists) router.push("/");
      else {
        signOut(auth).then(() => {
          console.log("login");
        });
      }
    });
  };

  const googleLogin = () => {
    signInWithPopup(auth, googleProvider)
      .then((result) => {
        const user = result.user;
        console.log(user);
        checkIfUserIdExists(user.uid);
      })
      .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;
        console.log(errorMessage);
      });
  };

  const twitterLogin = () => {
    signInWithPopup(auth, twitterProvider)
      .then((result) => {
        const user = result.user;
        checkIfUserIdExists(user.uid);
      })
      .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;
        console.log(errorMessage);
        // ...
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>로그인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={styles.formContainer}>
        <Formik
          initialValues={{ email: "", password: "" }}
          onSubmit={(values, actions) => {
            signInWithEmailAndPassword(auth, values.email, values.password)
              .then((userCredential) => {
                // Signed in
                const user = userCredential.user;
                checkIfUserIdExists(user.uid);
                // ...
              })
              .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;
                actions.setSubmitting(false);
                console.log(errorMessage);
              });
          }}
        >
          {(props) => (
            <Form
              style={isWidthMinimized ? { width: "100%" } : { width: "49%" }}
            >
              <Field name="email" validate={validateName}>
                {({ field, form }) => (
                  <FormControl
                    isInvalid={form.errors.name && form.touched.name}
                  >
                    <h3>이메일</h3>
                    <Input
                      {...field}
                      type={"email"}
                      placeholder="이메일"
                      id="email"
                    />
                    {/* <FormErrorMessage>{form.errors.name}</FormErrorMessage> */}
                  </FormControl>
                )}
              </Field>
              <Field name="password" validate={validateName}>
                {({ field, form }) => (
                  <FormControl
                    isInvalid={form.errors.name && form.touched.name}
                  >
                    <h3>비밀번호</h3>
                    <Input
                      {...field}
                      type={"password"}
                      placeholder="비밀번호"
                      id="password"
                    />
                    {/* <FormErrorMessage>{form.errors.name}</FormErrorMessage> */}
                  </FormControl>
                )}
              </Field>
              <div className={styles.buttonContainer}>
                <MainButton
                  isLoading={props.isSubmitting}
                  type="submit"
                  text="로그인"
                />
                <p style={{ margin: "0 1rem" }}>또는</p>
                <button
                  className={styles.iconButton}
                  style={{ border: "1px solid #DEE2E6" }}
                  onClick={googleLogin}
                >
                  <FcGoogle className={styles.socialIcon} />
                </button>
                <button
                  className={styles.iconButton}
                  style={{ backgroundColor: "#1e99e6", marginLeft: "0.25rem" }}
                  onClick={twitterLogin}
                >
                  <FaTwitter
                    className={styles.socialIcon}
                    style={{ color: "white" }}
                  />
                </button>
                {/* <button
                  className={styles.iconButton}
                  style={{ backgroundColor: "#3b5897", marginLeft: "0.25rem" }}
                >
                  <FaFacebookSquare
                    className={styles.socialIcon}
                    style={{ color: "white" }}
                  />
                </button> */}
              </div>
            </Form>
          )}
        </Formik>
        {isWidthMinimized ? null : (
          <div style={{ width: "49%" }} className={styles.contentContainer}>
            <h1>Login to Launchable</h1>
            <h1>Connect with other indie hackers running online businesses.</h1>
            <br></br>
            <h1>
              Get feedback on your business ideas, landing pages, and more.
            </h1>
            <br />
            <h1>Get the best new stories from founders in your inbox.</h1>
          </div>
        )}
      </div>
    </div>
  );
}
