import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import useSWR from "swr";
import styles from "../../styles/Settings.module.css";
import Header from "../../components/main/Header";
import { MdOutlineEdit } from "react-icons/md";
import { Button, Avatar, Center } from "@chakra-ui/react";
import axios from "axios";

import { useAuth } from "../../components/auth/AuthContext";

export default function Settings() {
  const { currentUser, userData } = useAuth();
  const router = useRouter();
  if (!currentUser) router.push("/signup");
  const fetcher = (url) =>
    axios({
      method: "post",
      url: url,
      data: JSON.stringify({
        id: userData.id,
      }),
      headers: {
        "Content-Type": "application/json",
      },
    }).then((res) => {
      return res.data.userData;
    });
  const { data, error } = useSWR(
    process.env.NEXT_PUBLIC_API_ROUTE + "api/auth",
    fetcher
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Launchable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={styles.headerContainer}>
        <Avatar
          src={
            "https://velog.velcdn.com/images/jinyoungbang/profile/f2430d79-f855-4ffd-9b97-66cc5b686784/image.jpeg"
          }
          style={{
            height: "10rem",
            width: "10rem",
          }}
        />
        <div className={styles.usernameContainer}>
          <div className={styles.usernameEditContainer}>
            <h2>@{data && data.username}</h2>
            <Link href="/settings/edit">
              <Button
                variant="solid"
                style={{
                  backgroundColor: "#038A64",
                  color: "#FFFFFF",
                  marginLeft: "1rem",
                  height: "2.5rem",
                  width: "2.5rem",
                }}
              >
                <Center>
                  <MdOutlineEdit style={{ color: "#ffffff" }} />
                </Center>
              </Button>
            </Link>
          </div>
        </div>
      </div>

      <div>
        <h3>Email</h3>
        <p>{data && data.email}</p>
      </div>
      <br></br>
      <div>
        <h3>Name</h3>
        <p>
          {""}
          {data && data.profile.display_name}
        </p>
      </div>
      <br></br>
      <div>
        <h3>About</h3>
        {data && data.profile.about}
      </div>
      <br></br>
      <div>
        <h3>Email</h3>
        <p>{data && data.email}</p>
      </div>

      <br />
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          2022, Launchable by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
