import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "../../../styles/user/Username.module.css";
import mainStyles from "../../../styles/Main.module.css";
import Header from "../../../components/main/Header";
import useSWR from "swr";
import axios from "axios";
import Loader from "../../../components/main/Loader";
import { Button, Avatar, Center } from "@chakra-ui/react";
import { Tabs, TabList, TabPanels, Tab, TabPanel } from "@chakra-ui/react";
import PostBox from "../../../components/user/PostBox";
import UserInfoBox from "../../../components/user/UserInfoBox";

export default function User() {
  const router = useRouter();
  const { username } = router.query;

  const fetcher = (url) =>
    axios({
      method: "get",
      url: url,
    }).then((res) => {
      return res.data;
    });

  const { data, error } = useSWR(
    process.env.NEXT_PUBLIC_API_ROUTE + "api/auth/username/" + username,
    fetcher
  );

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (data) {
      console.log(data);
      setIsLoading(false);
    }
  }, [data]);

  if (isLoading) return <Loader />;

  return (
    <div>
      <Head>
        <title>{data && data.user_data.username}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={mainStyles.container}>
        <div className={styles.headerContainer}>
          <Avatar
            src={data.user_data.profile.avatar_url}
            style={{
              height: "10rem",
              width: "10rem",
            }}
          />
          <div className={styles.usernameContainer}>
            <h2>@{data && data.user_data.username}</h2>
            <p>joined x days ago.</p>
          </div>
        </div>
        <div>
          <div className={styles.userDataContainer}>
            <Tabs variant="soft-rounded" style={{ width: "100%" }}>
              <TabList style={{ marginBottom: "1rem" }}>
                <Tab
                  style={{
                    width: "6rem",
                    padding: "0.5rem 0rem",
                  }}
                  _selected={{
                    color: "white",
                    bg: "#038a64",
                  }}
                >
                  포스트
                </Tab>
                <Tab
                  style={{
                    width: "6rem",
                    padding: "0.5rem 0rem",
                  }}
                  _selected={{
                    color: "white",
                    bg: "#038a64",
                  }}
                >
                  소개
                </Tab>
              </TabList>
              <TabPanels>
                <TabPanel>
                  {data.posts_data.map((post) => (
                    <PostBox
                      title={post.title}
                      body={post.body}
                      created_at={post.created_at}
                      id={post.id}
                      comments_count={post.comments_count}
                      likes_count={post.likes_count}
                    />
                  ))}
                </TabPanel>
                <TabPanel>
                  <UserInfoBox about={data.user_data.profile.about} />
                </TabPanel>
              </TabPanels>
            </Tabs>
          </div>
        </div>
      </div>
      <br />
      <br />
    </div>
  );
}
